# This is a basic example pyreleaser file which can be updated
# and extended for your project's needs.
#
# See the documentation at: github.com/edaniszewski/python_releaser

project_name: python_releaser
changelog:
  skip: true
checksum:
  name_template: checksum.txt